// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class about {
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.Label lblAbout;
		
		protected System.Web.UI.WebControls.HyperLink lnkWeb;
		
		protected System.Web.UI.WebControls.Label lblEnv;
		
		protected System.Web.UI.WebControls.Label lblInstance;
		
		protected System.Web.UI.WebControls.Label lblDatabaseAddress;
		
		protected System.Web.UI.WebControls.Label lblDatabaseName;
		
		protected System.Web.UI.WebControls.Label lblVersion;
		
		protected System.Web.UI.WebControls.Label lblBuild;
		
		protected System.Web.UI.WebControls.HyperLink lnkEmail;
	}
}
