// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class cloudEdit {
		
		protected System.Web.UI.WebControls.Content cHead;
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.HiddenField hidSortColumn;
		
		protected System.Web.UI.WebControls.HiddenField hidPage;
		
		protected System.Web.UI.WebControls.TextBox txtSearch;
		
		protected System.Web.UI.WebControls.Literal ltClouds;
		
		protected System.Web.UI.WebControls.Literal ltProviders;
	}
}
