// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class ecosystemEdit {
		
		protected System.Web.UI.WebControls.Content cHead;
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.Label lblEcotemplateName;
		
		protected System.Web.UI.WebControls.TextBox txtEcosystemName;
		
		protected System.Web.UI.WebControls.TextBox txtDescription;
		
		protected System.Web.UI.WebControls.Label lblEcosystemNameHeader;
		
		protected System.Web.UI.WebControls.Literal ltItems;
		
		protected System.Web.UI.WebControls.HiddenField hidEcosystemID;
		
		protected System.Web.UI.WebControls.HiddenField hidEcoTemplateID;
		
		protected System.Web.UI.WebControls.HiddenField hidParamDelete;
	}
}
