// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class ecoTemplateEdit {
		
		protected System.Web.UI.WebControls.Content cHead;
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.TextBox txtEcoTemplateName;
		
		protected System.Web.UI.WebControls.TextBox txtDescription;
		
		protected System.Web.UI.WebControls.Label lblEcoTemplateHeader;
		
		protected System.Web.UI.WebControls.Label lblActionTitle;
		
		protected System.Web.UI.WebControls.PlaceHolder phActions;
		
		protected System.Web.UI.WebControls.HiddenField hidEcoTemplateID;
	}
}
