// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class loginDefaultsEdit {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.UpdatePanel udpLoginDefaults;
		
		protected System.Web.UI.WebControls.TextBox txtPassMaxAge;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvPassMaxAge;
		
		protected System.Web.UI.WebControls.RangeValidator rvPassMaxAge;
		
		protected System.Web.UI.WebControls.TextBox txtPassMaxAttempts;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvPassMaxAttempts;
		
		protected System.Web.UI.WebControls.RangeValidator rvPassMaxAttempts;
		
		protected System.Web.UI.WebControls.TextBox txtPassMaxLength;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvPassMaxLength;
		
		protected System.Web.UI.WebControls.RangeValidator rvPassMaxLength;
		
		protected System.Web.UI.WebControls.TextBox txtPassMinLength;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvPassMinLength;
		
		protected System.Web.UI.WebControls.RangeValidator rvPassMinLength;
		
		protected System.Web.UI.WebControls.CheckBox cbPassComplexity;
		
		protected System.Web.UI.WebControls.TextBox txtPassAgeWarn;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvPassAgeWarn;
		
		protected System.Web.UI.WebControls.RangeValidator rvPassAgeWarn;
		
		protected System.Web.UI.WebControls.TextBox txtPasswordHistory;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvPasswordHistory;
		
		protected System.Web.UI.WebControls.RangeValidator rvPasswordHistory;
		
		protected System.Web.UI.WebControls.CheckBox cbPassRequireInitialChange;
		
		protected System.Web.UI.WebControls.TextBox txtAutoLockReset;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvAutoLockReset;
		
		protected System.Web.UI.WebControls.RangeValidator rvAutoLockReset;
		
		protected System.Web.UI.WebControls.TextBox txtLoginMessage;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvLoginMessage;
		
		protected System.Web.UI.WebControls.TextBox txtAuthErrorMessage;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rfvAuthErrorMessage;
		
		protected System.Web.UI.WebControls.TextBox txtNewUserMessage;
		
		protected System.Web.UI.WebControls.CheckBox cbPageViewLogging;
		
		protected System.Web.UI.WebControls.CheckBox cbReportViewLogging;
		
		protected System.Web.UI.WebControls.CheckBox cbAllowLogin;
		
		protected System.Web.UI.WebControls.Label lblMessage;
		
		protected System.Web.UI.WebControls.Button btnSave;
	}
}
