// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class notificationEdit {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.DropDownList ddlMessengerOnOff;
		
		protected System.Web.UI.WebControls.TextBox txtPollLoop;
		
		protected System.Web.UI.WebControls.TextBox txtRetryDelay;
		
		protected System.Web.UI.WebControls.TextBox txtRetryMaxAttempts;
		
		protected System.Web.UI.WebControls.TextBox txtRefreshMinutes;
		
		protected System.Web.UI.WebControls.TextBox txtSMTPServerAddress;
		
		protected System.Web.UI.WebControls.TextBox txtSMTPUserAccount;
		
		protected System.Web.UI.WebControls.TextBox txtSMTPUserPassword;
		
		protected System.Web.UI.WebControls.TextBox txtSMTPPasswordConfirm;
		
		protected System.Web.UI.WebControls.TextBox txtSMTPServerPort;
		
		protected System.Web.UI.WebControls.TextBox txtFromEmail;
		
		protected System.Web.UI.WebControls.TextBox txtFromName;
		
		protected System.Web.UI.WebControls.TextBox txtAdminEmail;
		
		protected System.Web.UI.WebControls.Button btnSave;
		
		protected System.Web.UI.WebControls.Label lblMessage;
	}
}
