// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class schedulerSettings {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.UpdatePanel udpNotifications;
		
		protected System.Web.UI.WebControls.DropDownList ddlSchedulerOnOff;
		
		protected System.Web.UI.WebControls.TextBox txtLoopDelay;
		
		protected System.Web.UI.WebControls.TextBox txtScheduleMinDepth;
		
		protected System.Web.UI.WebControls.TextBox txtScheduleMaxDays;
		
		protected System.Web.UI.WebControls.TextBox txtCleanAppRegistry;
		
		protected System.Web.UI.WebControls.Button btnSave;
		
		protected System.Web.UI.WebControls.Label lblMessage;
	}
}
