// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web {
	
	
	public partial class sitemaster {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder phHead;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.ScriptManager ScriptManager;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder phDetail;
		
		protected System.Web.UI.WebControls.PlaceHolder phMenu;
		
		protected System.Web.UI.WebControls.DropDownList ddlCloudAccounts;
	}
}
