// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class systemStatusView {
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.Repeater rpSystemComponents;
		
		protected System.Web.UI.WebControls.HyperLink lnkCELogFile;
		
		protected System.Web.UI.WebControls.Repeater rptUsers;
	}
}
