// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class taskStatusView {
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskProcessing;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskStaged;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskSubmitted;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskPending;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskAborting;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskQueued;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskActive;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskCompleted;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskCancelled;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskErrored;
		
		protected System.Web.UI.WebControls.Label lblAutomatedTaskTotalCompleted;
		
		protected System.Web.UI.WebControls.Label lblAutomatedAllStatuses;
	}
}
