// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class taskView {
		
		protected System.Web.UI.WebControls.Content cHead;
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl tab_schedules;
		
		protected System.Web.UI.WebControls.Label lblVersion;
		
		protected System.Web.UI.WebControls.Label lblStatus2;
		
		protected System.Web.UI.WebControls.Button btnSetDefault;
		
		protected System.Web.UI.WebControls.Label lblLastRunDT;
		
		protected System.Web.UI.WebControls.Label lblLastRunStatus;
		
		protected System.Web.UI.WebControls.Image debug_view_latest_log;
		
		protected System.Web.UI.WebControls.Label lblCurrentStatus;
		
		protected System.Web.UI.UpdatePanel udpSchedule;
		
		protected System.Web.UI.WebControls.Repeater rpSchedules;
		
		protected System.Web.UI.WebControls.Label lblTaskNameHeader;
		
		protected System.Web.UI.WebControls.Label lblVersionHeader;
		
		protected System.Web.UI.WebControls.Label lblTaskCode;
		
		protected System.Web.UI.WebControls.Label lblStatus;
		
		protected System.Web.UI.WebControls.Label lblConcurrentInstances;
		
		protected System.Web.UI.WebControls.Label lblQueueDepth;
		
		protected System.Web.UI.WebControls.Label lblDescription;
		
		protected System.Web.UI.WebControls.Repeater rpAttributeGroups;
		
		protected System.Web.UI.WebControls.Repeater rpGroupAttributes;
		
		protected System.Web.UI.WebControls.PlaceHolder phSteps;
		
		protected System.Web.UI.WebControls.Label lblCurrentVersion;
		
		protected System.Web.UI.WebControls.Label lblNewMinor;
		
		protected System.Web.UI.WebControls.Label lblNewMajor;
		
		protected System.Web.UI.WebControls.HiddenField hidOriginalTaskID;
		
		protected System.Web.UI.WebControls.HiddenField hidTaskID;
		
		protected System.Web.UI.WebControls.HiddenField hidDefault;
		
		protected System.Web.UI.WebControls.HiddenField hidDebugActiveInstance;
	}
}
