// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class taskActivityLog {
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.HiddenField hidSortColumn;
		
		protected System.Web.UI.WebControls.HiddenField hidPage;
		
		protected System.Web.UI.UpdatePanel uplTaskActivity;
		
		protected System.Web.UI.WebControls.TextBox txtSearch;
		
		protected System.Web.UI.WebControls.TextBox txtStartDate;
		
		protected System.Web.UI.WebControls.TextBox txtStopDate;
		
		protected System.Web.UI.WebControls.TextBox txtResultCount;
		
		protected System.Web.UI.WebControls.ImageButton btnSearch;
		
		protected System.Web.UI.WebControls.Repeater rpTaskInstances;
		
		protected System.Web.UI.WebControls.HyperLink lnkEdit;
		
		protected System.Web.UI.WebControls.PlaceHolder phPager;
		
		protected System.Web.UI.WebControls.Button btnGetPage;
	}
}
