// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class taskPrint {
		
		protected System.Web.UI.WebControls.Content cHead;
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.Label lblTaskNameHeader;
		
		protected System.Web.UI.WebControls.Label lblVersionHeader;
		
		protected System.Web.UI.WebControls.ImageButton btnExport;
		
		protected System.Web.UI.WebControls.HiddenField hidExport;
		
		protected System.Web.UI.WebControls.Label lblTaskCode;
		
		protected System.Web.UI.WebControls.Label lblStatus;
		
		protected System.Web.UI.WebControls.Label lblConcurrentInstances;
		
		protected System.Web.UI.WebControls.Label lblQueueDepth;
		
		protected System.Web.UI.WebControls.Label lblDescription;
		
		protected System.Web.UI.WebControls.Repeater rpAttributeGroups;
		
		protected System.Web.UI.WebControls.Repeater rpGroupAttributes;
		
		protected System.Web.UI.WebControls.PlaceHolder phParameters;
		
		protected System.Web.UI.WebControls.PlaceHolder phSteps;
	}
}
