// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class taskManage {
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.HiddenField hidSortColumn;
		
		protected System.Web.UI.WebControls.HiddenField hidSortDirection;
		
		protected System.Web.UI.WebControls.HiddenField hidLastSortColumn;
		
		protected System.Web.UI.WebControls.HiddenField hidPage;
		
		protected System.Web.UI.UpdatePanel udpTaskList;
		
		protected System.Web.UI.WebControls.TextBox txtSearch;
		
		protected System.Web.UI.WebControls.ImageButton btnSearch;
		
		protected System.Web.UI.WebControls.Repeater rpTasks;
		
		protected System.Web.UI.WebControls.PlaceHolder phPager;
		
		protected System.Web.UI.WebControls.Button btnGetPage;
		
		protected System.Web.UI.WebControls.TextBox txtTaskCode;
		
		protected System.Web.UI.WebControls.TextBox txtTaskName;
		
		protected System.Web.UI.WebControls.TextBox txtTaskDesc;
		
		protected System.Web.UI.WebControls.TextBox txtCopyTaskCode;
		
		protected System.Web.UI.WebControls.TextBox txtCopyTaskName;
	}
}
