// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class taskRunLog {
		
		protected System.Web.UI.WebControls.Content cHead;
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.Label lblBackLink;
		
		protected System.Web.UI.WebControls.Label lblTaskName;
		
		protected System.Web.UI.WebControls.Label lblTaskInstance;
		
		protected System.Web.UI.WebControls.Label lblStatus;
		
		protected System.Web.UI.WebControls.Label lblStartedDT;
		
		protected System.Web.UI.WebControls.Label lblCompletedDT;
		
		protected System.Web.UI.WebControls.PlaceHolder phCancel;
		
		protected System.Web.UI.WebControls.PlaceHolder phResubmit;
		
		protected System.Web.UI.WebControls.Label lblAccountName;
		
		protected System.Web.UI.WebControls.Label lblSubmittedBy;
		
		protected System.Web.UI.WebControls.Label lblEcosystemName;
		
		protected System.Web.UI.WebControls.Label lblSubmittedDT;
		
		protected System.Web.UI.WebControls.Label lblAssetName;
		
		protected System.Web.UI.WebControls.Label lblSubmittedByInstance;
		
		protected System.Web.UI.WebControls.Label lblCENode;
		
		protected System.Web.UI.WebControls.Label lblPID;
		
		protected System.Web.UI.WebControls.Panel pnlOtherInstances;
		
		protected System.Web.UI.WebControls.Repeater rpOtherInstances;
		
		protected System.Web.UI.WebControls.PlaceHolder phLog;
		
		protected System.Web.UI.WebControls.Label lblResubmitMessage;
		
		protected System.Web.UI.WebControls.HiddenField hidTaskID;
		
		protected System.Web.UI.WebControls.HiddenField hidAssetID;
		
		protected System.Web.UI.WebControls.HiddenField hidEcosystemID;
		
		protected System.Web.UI.WebControls.HiddenField hidAccountID;
		
		protected System.Web.UI.WebControls.HiddenField hidInstanceID;
		
		protected System.Web.UI.WebControls.HiddenField hidSubmittedByInstance;
		
		protected System.Web.UI.WebControls.HiddenField hidRows;
		
		protected System.Web.UI.WebControls.HiddenField hidCELogFile;
		
		protected System.Web.UI.WebControls.HiddenField hidDebugLevel;
	}
}
