// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class taskStepVarsEdit {
		
		protected System.Web.UI.WebControls.Content cHead;
		
		protected System.Web.UI.WebControls.Content cDetail;
		
		protected System.Web.UI.WebControls.Label lblTaskName;
		
		protected System.Web.UI.WebControls.Label lblCommandName;
		
		protected System.Web.UI.WebControls.PlaceHolder phVars;
		
		protected System.Web.UI.WebControls.HiddenField hidStepID;
		
		protected System.Web.UI.WebControls.HiddenField hidOutputParseType;
		
		protected System.Web.UI.WebControls.HiddenField hidRowDelimiter;
		
		protected System.Web.UI.WebControls.HiddenField hidColDelimiter;
	}
}
