// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web.pages {
	
	
	public partial class userPreferenceEdit {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.UpdatePanel udpUserPreferences;
		
		protected System.Web.UI.WebControls.Label lblName;
		
		protected System.Web.UI.WebControls.Label lblUserName;
		
		protected System.Web.UI.WebControls.Label lblAuthenticationType;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.HiddenField hidEmail;
		
		protected System.Web.UI.WebControls.Panel pnlLocalSettings;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.TextBox txtPasswordConfirm;
		
		protected System.Web.UI.WebControls.TextBox txtSecurityQuestion;
		
		protected System.Web.UI.WebControls.TextBox txtSecurityAnswer;
		
		protected System.Web.UI.WebControls.HiddenField hidSecurityAnswer;
		
		protected System.Web.UI.WebControls.Button btnSave;
		
		protected System.Web.UI.WebControls.Label lblMessage;
	}
}
