// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Web {
	
	
	public partial class login {
		
		protected System.Web.UI.WebControls.Literal ltTitle;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblErrorMessage;
		
		protected System.Web.UI.WebControls.Label lblMessage;
		
		protected System.Web.UI.WebControls.Panel pnlLogin;
		
		protected System.Web.UI.WebControls.Label lblLoginUser;
		
		protected System.Web.UI.WebControls.TextBox txtLoginUser;
		
		protected System.Web.UI.WebControls.Label lblLoginPassword;
		
		protected System.Web.UI.WebControls.TextBox txtLoginPassword;
		
		protected System.Web.UI.WebControls.Button btnLogin;
		
		protected System.Web.UI.WebControls.Button btnForgotPassword;
		
		protected System.Web.UI.WebControls.Panel pnlForgotPassword;
		
		protected System.Web.UI.WebControls.Label lblRecoverMessage;
		
		protected System.Web.UI.WebControls.Label lblRecoverUserName;
		
		protected System.Web.UI.WebControls.Panel pnlPasswordReset;
		
		protected System.Web.UI.WebControls.Label lblSecurityQuestion;
		
		protected System.Web.UI.WebControls.TextBox txtSecurityAnswer;
		
		protected System.Web.UI.WebControls.TextBox txtResetPassword;
		
		protected System.Web.UI.WebControls.TextBox txtResetPasswordConfirm;
		
		protected System.Web.UI.WebControls.Button btnResetPassword;
		
		protected System.Web.UI.WebControls.Button btnCancelPasswordReset;
		
		protected System.Web.UI.WebControls.Panel pnlNoQaOnFile;
		
		protected System.Web.UI.WebControls.Button btnCancelNoQa;
		
		protected System.Web.UI.WebControls.Panel pnlResetPassword;
		
		protected System.Web.UI.WebControls.Label lblResetMessage;
		
		protected System.Web.UI.WebControls.Label lblUserName;
		
		protected System.Web.UI.WebControls.TextBox txtCurrentPassword;
		
		protected System.Web.UI.WebControls.TextBox txtNewPassword;
		
		protected System.Web.UI.WebControls.TextBox txtNewPasswordConfirm;
		
		protected System.Web.UI.WebControls.Button btnNewPassword;
		
		protected System.Web.UI.WebControls.Button btnCancelNewPassword;
		
		protected System.Web.UI.WebControls.Panel pnlExpireWarning;
		
		protected System.Web.UI.WebControls.Label lblExpireWarning;
		
		protected System.Web.UI.WebControls.Label lblWarnUsername;
		
		protected System.Web.UI.WebControls.TextBox txtWarningCurrentPassword;
		
		protected System.Web.UI.WebControls.TextBox txtWarningNewPassword;
		
		protected System.Web.UI.WebControls.TextBox txtWarningNewPasswordConfirm;
		
		protected System.Web.UI.WebControls.Button btnExpiredPassword;
		
		protected System.Web.UI.WebControls.Button btnUpdateLater;
		
		protected System.Web.UI.WebControls.HiddenField hidUpdateLater;
		
		protected System.Web.UI.WebControls.HiddenField hidID;
	}
}
